
SYNTROPY_API_KEY: "XtZtgiLnodBZ5CIBVcmr8q9cGN17WpVq"
SYNTROPY_PROVIDER_NODE: "16"
SYNTROPY_AGENT_NAME_NODE: "eth"
SYNTROPY_PROVIDER_M: "3"
SYNTROPY_AGENT_NAME_M: "monitoring"



GRAFANA_USERNAME: "admin"
GRAFANA_PASSWORD: "akvariumas123"